# Generated by Django 5.2.16 on 2026-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_category_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prep_time',
            field=models.CharField(default='15-20 mins', max_length=50),
        ),
    ]
